export const MUSIC_GENRES = [
  "Pop",
  "Rock",
  "Heavy Metal",
  "Afro House",
  "Hip Hop",
  "R&B",
  "Jazz",
  "Blues",
  "Country",
  "Folk",
  "Electronic",
  "Techno",
  "House",
  "Trance",
  "Dubstep",
  "Drum & Bass",
  "Reggae",
  "Ska",
  "Punk",
  "Indie Rock",
  "Alternative Rock",
  "Classic Rock",
  "Progressive Rock",
  "Psychedelic Rock",
  "Grunge",
  "Emo",
  "Post-Rock",
  "Math Rock",
  "Shoegaze",
  "Gothic Rock",
  "Death Metal",
  "Black Metal",
  "Thrash Metal",
  "Power Metal",
  "Progressive Metal",
  "Nu Metal",
  "Metalcore",
  "Deathcore",
  "Hardcore Punk",
  "Pop Punk",
  "Ska Punk",
  "Folk Punk",
  "Celtic Punk",
  "Garage Rock",
  "Surf Rock",
  "Rockabilly",
  "Psychobilly",
  "Glam Rock",
  "Arena Rock",
  "Southern Rock",
  "Blues Rock",
  "Jazz Rock",
  "Fusion",
  "Funk",
  "Soul",
  "Motown",
  "Disco",
  "New Wave",
  "Synthpop",
  "Electropop",
  "Dream Pop",
  "Chillwave",
  "Vaporwave",
  "Lo-fi",
  "Ambient",
  "Downtempo",
  "Trip Hop",
  "IDM",
  "Breakbeat",
  "Big Beat",
  "Acid Jazz",
  "Nu Jazz",
  "Smooth Jazz",
  "Bebop",
  "Cool Jazz",
  "Free Jazz",
  "Avant-garde Jazz",
  "Latin Jazz",
  "Afro-Cuban Jazz",
  "Bossa Nova",
  "Samba",
  "Tango",
  "Flamenco",
  "Mariachi",
  "Cumbia",
  "Salsa",
  "Merengue",
  "Bachata",
  "Reggaeton",
  "Dembow",
  "Afrobeats",
  "Afropop",
  "Highlife",
  "Juju",
  "Fuji",
  "Apala",
  "Waka",
  "Makossa",
  "Soukous",
  "Rumba",
  "Mbalax",
  "Kizomba",
  "Kuduro",
  "Zouk",
  "Samba Reggae",
  "Axé",
  "Forró",
  "Pagode",
  "MPB",
  "Tropicalia",
  "Baião",
  "Xote",
  "Frevo",
  "Maracatu",
  "Gospel",
  "Christian Rock",
  "Contemporary Christian",
  "Worship",
  "Hymns",
  "Spirituals",
  "Blues Gospel",
  "Country Gospel",
  "Southern Gospel",
  "Black Gospel",
  "Contemporary Gospel",
  "Urban Gospel",
  "Classical",
  "Baroque",
  "Romantic",
  "Modern Classical",
  "Contemporary Classical",
  "Minimalism",
  "Opera",
  "Operetta",
  "Musical Theatre",
  "Film Score",
  "Video Game Music",
  "New Age",
  "World Music",
  "Traditional Folk",
  "Celtic",
  "Irish Folk",
  "Scottish Folk",
  "English Folk",
  "American Folk",
  "Bluegrass",
  "Old-Time",
  "Appalachian",
  "Cajun",
  "Zydeco",
  "Tejano",
  "Norteño",
  "Corrido",
  "Ranchera",
  "Bolero",
  "Vals",
  "Polka",
  "Waltz",
  "Mazurka",
  "Polonaise",
  "Tarantella",
  "Fandango",
  "Sevillanas",
  "Fado",
  "Rebetiko",
  "Klezmer",
  "Gypsy Jazz",
  "Romani Music",
  "Balkan Music",
  "Turkish Folk",
  "Arabic Music",
  "Persian Music",
  "Indian Classical",
  "Carnatic",
  "Hindustani",
  "Qawwali",
  "Ghazal",
  "Bhajan",
  "Kirtan",
  "Chinese Opera",
  "Peking Opera",
  "Cantonese Opera",
  "Japanese Traditional",
  "Gagaku",
  "Noh",
  "Kabuki",
  "Korean Traditional",
  "Pansori",
  "Gugak",
  "Thai Classical",
  "Gamelan",
  "Wayang Kulit",
  "Kecak",
  "Balinese Music",
  "Javanese Music",
  "Sundanese Music",
  "Filipino Folk",
  "Kundiman",
  "Harana",
  "Tinikling",
  "Cariñosa",
  "Pandanggo",
  "Kuratsa",
  "Subli",
  "Sayaw sa Bangko",
  "Vietnamese Folk",
  "Ca Trù",
  "Hát Chèo",
  "Hát Xẩm",
  "Quan Họ",
  "Hát Then",
  "Hát Ví",
  "Hát Dặm",
  "Mongolian Folk",
  "Throat Singing",
  "Khoomei",
  "Tuvan Music",
  "Kazakh Music",
  "Kyrgyz Music",
  "Uzbek Music",
  "Tajik Music",
  "Turkmen Music",
  "Azerbaijani Music",
  "Georgian Folk",
  "Armenian Folk",
  "Russian Folk",
  "Ukrainian Folk",
  "Belarusian Folk",
  "Polish Folk",
  "Czech Folk",
  "Slovak Folk",
  "Hungarian Folk",
  "Romanian Folk",
  "Bulgarian Folk",
  "Serbian Folk",
  "Croatian Folk",
  "Slovenian Folk",
  "Bosnian Folk",
  "Montenegrin Folk",
  "Macedonian Folk",
  "Albanian Folk",
  "Greek Folk",
  "Maltese Folk",
  "Italian Folk",
  "Spanish Folk",
  "Portuguese Folk",
  "French Folk",
  "Belgian Folk",
  "Dutch Folk",
  "German Folk",
  "Austrian Folk",
  "Swiss Folk",
  "Danish Folk",
  "Norwegian Folk",
  "Swedish Folk",
  "Finnish Folk",
  "Icelandic Folk",
  "Estonian Folk",
  "Latvian Folk",
  "Lithuanian Folk",
  "Tech house",
  "EDM",
];
